FROM bitnami/tomcat
MAINTAINER Carlos Telleria

ADD *.jar /opt/bitnami/tomcat/lib/
ADD context.xml /opt/bitnami/tomcat/conf/
ADD server.xml /opt/bitnami/tomcat/conf/

ADD helloWorld.war /opt/bitnami/tomcat/webapps/







